import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "../components/Button";
import {
  AcademyIcon,
  IdeaIcon,
  GraphicIcon,
  PeopleIcon,
  HatIcon,
  DownArrow,
  NextIcon,
  BottomFigure
} from "../components/icons";
import Header from "../components/Header";
import { Card } from "../components/Card";
import TestimonialCard, {
  TestimonialCardProps,
} from "../components/TestimonialCard";
import { useRef, useState } from "react";
import FaqCard from "../components/FaqCard";
import FDC from "/public/FDC.svg";

import EquisAccredited from "/public/EquisAccredited.png";
import FTImage from "/public/FT.png";
import MBA from "/public/MBA.png";
import Rectangle1 from "/public/Rectangle21.png";
import Rectangle2 from "/public/Rectangle22.png";
import Rectangle3 from "/public/Rectangle23.png";
import { Navigation, Pagination, Scrollbar, A11y, Grid } from "swiper";
import { Swiper, SwiperSlide, useSwiper } from "swiper/react";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination"
import "swiper/css/scrollbar";
import "swiper/css/grid";
import Canvas from "../components/Canvas";
import Footer from "../components/Footer";
import InfoCard from "../components/InfoCard";
import AnimatedCanvas from "../components/AnimatedCanvas";
import CustomSwiper from "../components/CustomSwiper";
import Webdoor from '../components/LP/Webdoor'
import Cards from '../components/LP/Cards'
export default function Home() {
  
  const testimonial = {
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo reiciendis quasi, fugit velit deserunt ex aut nesciunt tempore odit et asperiores non illum nam tempora odio rerum sapiente amet unde.",
    author: "Lorem Ipsum",
    role: "vp de blá blá blá",
  };
  const faq = {
    title:
      "Como participar do programa Corporate - Learn & Drive para empresas da FDC?",
    children: (
      <>
        <p>
          {" "}
          Para participar do programa, é necessário realizar o cadastro da sua
          empresa e responder à avaliação de maturidade criada por especialistas
          da Fundação Dom Cabral.
        </p>
        <p>
          {" "}
          Após concluí-lo, você receberá o raio-x completo da empresa, dividido
          em 7 dimensões, sendo elas: Liderança & Pessoas, Gestão Estratégica
          dos Negócios, Marketing & Vendas, Finanças, Governança & Compliance,
          Inovação & Transformação Digital e Gestão Estratégica de Supply - com
          uma sugestão de trilha de desenvolvimento elaborada pela FDC
          especialmente para sua organização.
        </p>
      </>
    ),
  };
  const navPrevButton = useRef<HTMLButtonElement>(null);
  const navNextButton = useRef<HTMLButtonElement>(null);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <Webdoor />
        {/* Seção dos cards */}
        <Cards />
        {/*  */}
        <article className="bg-primary-gray-dark relative pt-44 overflow-x-hidden -z-1 text-white ">
          <div className="relative z-10 max-md:px-8 lg:max-w-article center">
            <section className="heading border-[#686366]">
              <h2 className="heading-text text-primary-blue uppercase font-light">
                Sobre a fdc
              </h2>
            </section>
            <section className="">
              <div className="max-w-lg mx-auto">
                <p className="py-12">
                  A FDC impulsiona o desenvolvimento das organizações com uma
                  abordagem focada em resultados, inclusão e sustentabilidade
                  para os negócios. Olhamos para a real necessidade, bem como
                  para os desafios e objetivos das organizações e de seus
                  profissionais, contribuindo para o aprimoramento das
                  competências gerenciais e individuais e a melhoria constante
                  da governança, gestão e dos resultados.
                </p>
              </div>
              <section className="flex flex-col gap-y-8 max-w-3xl mx-auto ">
                <div className="flex gap-6 max-lg:flex-col-reverse max-lg:px-8">
                  <InfoCard strongColor="bg-terciary-orange" className="flex-grow" strongText="45 Anos">de história de sucesso e liderança</InfoCard>
                  <InfoCard strongColor="bg-terciary-orange" className="flex-grow" strongText="1 Milhão">de executivos capacitados em programas</InfoCard>
                  <InfoCard strongColor="bg-terciary-orange" className="flex-grow" strongText="700">docentes com notoriedade nacional e internacional</InfoCard>
                  <InfoCard strongColor="bg-terciary-orange" className="flex-grow" strongText="900">empresas cliente
                    atendidas por ano</InfoCard>
                </div>
                <div className="flex gap-6 max-lg:flex-col max-lg:px-8">
                  <InfoCard strongColor="bg-terciary-orange" className="" strongText="+37 mil">executivos participantes por ano</InfoCard>
                  <InfoCard strongColor="bg-terciary-orange" className="" strongText="1ª em Educação">Executiva na América Latina há 15 anos consecutivos*</InfoCard>
                  <InfoCard strongColor="bg-terciary-orange" className="" strongText="9ª melhor">escola de negócios do mundo*</InfoCard>
                </div>
              </section>
              <div className="mx-auto max-w-lg pt-9">
                <span>
                  *Segundo o ranking de Educação Executiva 2022 do Financial
                  Times.
                </span>
              </div>
              <Button
                theme="outline"
                className="text-white outline-white mx-auto mt-10 my-12"
              >
                Conheça Mais
              </Button>
            </section>
            <section className="flex gap-16 items-stretch max-lg:flex-col mx-auto max-w-3xl  px-12 py-14 mb-20  bg-white text-primary-gray-dark">
              <div className="flex flex-1 items-end self-center">
                <h3 className="before:content-['']  before:absolute before:w-1/2 before:h-2 before:-top-4 before:bg-terciary-orange relative font-nexaSlab  font">
                  Ranking e Certificações
                </h3>
              </div>
              <div className="flex gap-6 items-center max-lg:flex-col justify-around">
                <img src={FTImage.src} alt="" className="h-14" />
                <img src={MBA.src} alt="" className="h-10" />
                <img src={EquisAccredited.src} alt="" className="h-16" />
              </div>
            </section>
          </div>
          <CustomSwiper
            modules={[Navigation, Pagination, Scrollbar, A11y, Grid]}
            spaceBetween={0}
            swiperName="custom-inside"
            pagination
            breakpoints={{
              768: {
                spaceBetween: 0,
                slidesPerView: 3,
              },
            }}
          >
            <SwiperSlide>
              <div className="flex-1">
                <img src={Rectangle1.src} alt="" className="w-full" />
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <img src={Rectangle2.src} alt="" className="w-full" />
            </SwiperSlide>
            <SwiperSlide>
              <img src={Rectangle3.src} alt="" className="w-full" />
            </SwiperSlide>
          </CustomSwiper>

          <div className="absolute bottom-1 left-1/2 -translate-x-1/2">
            <FDC className="h-[634px] text-[#686366] z-1" />
          </div>
        </article>
        <article className="py-28 bg-white relative overflow-hidden max-md:px-8">
          <div className="relative z-10 ">
            <section className="heading border-secondary-gray-medium max-w-article center">
              <h2 className="heading-text text-primary-blue">
                Sua empresa em boa companhia
              </h2>
            </section>
            <section className="mx-auto max-w-lg py-12 text-primary-gray-dark">
              <p>
                Confira os depoimentos de executivos e colaboradores que já
                participaram de programas empresariais da FDC
              </p>
            </section>
            <section className="center px-8 relative">
              <CustomSwiper
                modules={[Navigation, Pagination, Scrollbar, A11y]}
                spaceBetween={16}
                swiperName="custom"
                slidesPerView={1}
                pagination
                breakpoints={{
                  1024: {
                    width: 1024,
                    slidesPerView: 3
                  },
                  768: {
                    width: 768,
                    slidesPerView: 2,
                  }
                }}
                navigation={{
                  prevEl: navPrevButton.current,
                  nextEl: navNextButton.current,
                }}

                onBeforeInit={(swiper) => {
                  (swiper.params.navigation.prevEl = navPrevButton.current);
                  (swiper.params.navigation.nextEl = navNextButton.current);
                }}
              >
                <SwiperSlide >
                  <TestimonialCard data={testimonial}></TestimonialCard>
                </SwiperSlide>
                <SwiperSlide>
                  <TestimonialCard data={testimonial}></TestimonialCard>
                </SwiperSlide>
                <SwiperSlide>
                  <TestimonialCard data={testimonial}></TestimonialCard>
                </SwiperSlide>
                <SwiperSlide>
                  <TestimonialCard data={testimonial}></TestimonialCard>
                </SwiperSlide>
                <SwiperSlide>
                  <TestimonialCard data={testimonial}></TestimonialCard>
                </SwiperSlide>
                <SwiperSlide>
                  <TestimonialCard data={testimonial}></TestimonialCard>
                </SwiperSlide>
              </CustomSwiper>
              <div className="text-primary-blue max-md:hidden">
                <button
                  className="absolute top-1/2 -translate-y-1/2 left-0 -translate-x-1/4 rotate-90"
                  ref={navPrevButton}
                >
                  <DownArrow className="h-8" />
                </button>
                <button
                  ref={navNextButton}
                  className="absolute top-1/2 -translate-y-1/2 right-0 translate-x-1/4 -rotate-90"
                >
                  <DownArrow className="h-8" />
                </button>
              </div>
            </section>
          </div>
          <div className="absolute -bottom-1/2 left-1/2 -translate-x-1/2">
            <FDC className="h-[634px] text-secondary-gray-medium z-1" />
          </div>
        </article>
        <article className="flex center justify-between center py-32 max-lg:flex-col gap-8 max-lg:items-center max-md:px-8">
          <section className="heading flex-1 w-1/2 lg:max-w-xs border-white self-start  ">
            <h2 className="pb-2 text-4xl text-primary-blue uppercase">FAQ</h2>
          </section>
          <div className="px-8">
            <ol className="list-decimal flex flex-col marker:text-terciary-orange marker:font-bold divide-y divide-terciary-gray-blue divide-solid">
              <li className="pt-6">
                <FaqCard title={faq.title}>{faq.children}</FaqCard>
              </li>
              <li className="pt-6">
                <FaqCard title={faq.title}>{faq.children}</FaqCard>
              </li>
              <li className="pt-6">
                <FaqCard title={faq.title}>{faq.children}</FaqCard>
              </li>
              <li className="pt-6">
                <FaqCard title={faq.title}>{faq.children}</FaqCard>
              </li>
              <li className="pt-6">
                <FaqCard title={faq.title}>{faq.children}</FaqCard>
              </li>
            </ol>
          </div>
        </article>
      </div>
      <article className="bg-primary-black-blue relative text-white max-md:px-8">
        <section className="center max-w-lg py-32 relative z-10">
          <h2 className="font-nexaSlab text-2xl pb-8">
            Transforme os gaps do seu negócio em oportunidades com a FDC
          </h2>
          <div className="font-nexaSlab relative">
            <p className="before:content-[''] before:absolute before:w-1 before:h-full  before:-left-6 pb-6  before:bg-terciary-orange">
              Cadastre-se agora mesmo e faça a{" "}
              <strong>avaliação de maturidade</strong> da sua empresa
            </p>
            <Button theme="secondary">Quero começar agora</Button>
          </div>
        </section>
        <div className="absolute w-full h-full bottom-0 z-0">
          <AnimatedCanvas pointColor="rgba(42,159,188,0.75)" lineColor="rgba(42,159,188,0.75)" points="8" />
        </div>
      </article>
      <Footer />
    </div>
  );
}
