import Head from "next/head";
import Button from "../components/Button";
import Header from "../components/Header";
import Testimonials from '../components/LP/Testimonials'
import Footer from "../components/Footer";
import AnimatedCanvas from "../components/AnimatedCanvas";
import Webdoor from '../components/LP/Webdoor'
import Cards from '../components/LP/Cards'
import About from '../components/LP/About'
import Faq from "../components/LP/Faq";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Webdoor />
      {/* Seção dos cards */}
      <Cards />
      <About />
      <Testimonials />
      <Faq />
      <section className="bg-primary-black-blue relative overflow-hidden text-white max-md:px-8">
        <article className="center max-w-lg py-32 relative z-10">
          <h2 className="font-nexaSlab text-2xl pb-8">
            Transforme os gaps do seu negócio em oportunidades com a FDC
          </h2>
          <div className="font-nexaSlab relative">
            <p className="before:content-[''] before:absolute before:w-1 before:h-full  before:-left-6 pb-6  before:bg-terciary-orange">
              Cadastre-se agora mesmo e faça a{" "}
              <strong>avaliação de maturidade</strong> da sua empresa
            </p>
            <Button theme="secondary">Quero começar agora</Button>
          </div>
        </article>
        <div className="absolute w-full h-full bottom-0 z-0">
          <AnimatedCanvas pointColor="rgba(42,159,188,0.75)" lineColor="rgba(42,159,188,0.75)" pointQuantity="10" connectDistance="300" />
        </div>
      </section>
      <Footer />
    </div>
  );
}
